### ISSUE TITLE
0.95.57.eng.rar is not a whitelisted download

### ISSUE THREAD

**Issue by wjkmartin** [erri120/lotus#49]
420.2 - 0.95.57.eng.rar is not a whitelisted download
420.21 - Encountered error, can't continue - System.Exception: 1 validation errors found, cannot continue.
   at Wabbajack.Lib.Validation.ValidateModlist.RunValidation(WorkQueue queue, ModList modlist) in T:\test-agent\_work\1\s\Wabbajack.Lib\Validation\ValidateModlist.cs:line 60
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 85
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__49_0() in T:\test-agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 366

**To Reproduce**
Try to install Lotus

**Modlist version**
0.2.2

**Did you add any additional mods?**
No

**Comment by wjkmartin** [comment]
withdrawn

**Comment by whydoesthisaccexist** [comment]
how was this issue fixed? im having the same issue

**Comment by wjkmartin** [comment]
Will be fixed in the next major version update. Seems unnecessary to have it as an issue.
